---
# tasks file for pihole-update

- name: backup pihole
  ansible.builtin.command: 
   cmd: 'pihole -a -t'
  args:
    chdir: "{{ syncthing_dir }}"

- name: update pihole
  ansible.builtin.command: 
    cmd: 'pihole -up'

- name: add ninas work laptop domain to dnsmasq 
  ansible.builtin.template:
    src: 07-nina-work-laptop.conf.j2
    dest: /etc/dnsmasq.d/07-nina-work-laptop.conf
    backup: yes
  notify:
    - restart pihole-FTL

- name: update dnsmasq configuration to allow active-active dns
  ansible.builtin.template:
    src: 02-pihole-dhcp.conf.j2
    dest: /etc/dnsmasq.d/02-pihole-dhcp.conf
    backup: yes
  notify:
    - restart pihole-FTL
