---
# tasks file for pihole-update

- name: update apt cache
  apt:
    update_cache: yes

- name: update system
  apt:
    name: "*"
    state: latest
  notify:
    - reboot raspberry pi

- name: update pihole
  command: 'pihole -up'

- name: update dnsmasq configuration to allow active-active dns
  template:
    src: 02-pihole-dhcp.conf.j2
    dest: /etc/dnsmasq.d/02-pihole-dhcp.conf
    backup: yes
  notify:
    - restart pihole-FTL