---
- name: restart prometheus
  listen: "restart prometheus"
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: prometheus
    state: restarted
    enabled: true
  register: prometheus_restarted

- name: reload prometheus
  listen: "reload prometheus"
  become: true
  ansible.builtin.systemd:
    name: prometheus
    state: reloaded
    enabled: true
  when: prometheus_restarted is not defined