---
# playbook for updating rpis

- hosts: piholes
  any_errors_fatal: true
  gather_facts: true
  become: true
  tasks:
  - name: update apt cache
    apt:
      update_cache: yes

  - name: update system
    apt:
      name: "*"
      state: latest
    notify:
      - reboot raspberry pi

  - name: backup pihole
    chdir: "{{ syncthing_dir }}"
    command: 'pihole -a -t'

  - name: update pihole
    command: 'pihole -up'

  handlers:
    - name: reboot raspberry pi
      reboot: