---
# tasks file for sensor-setup

- name: update apt cache
  ansible.builtin.apt:
    update_cache: yes    

- name: install dependencies
  ansible.builtin.apt:
    name:
      - apache2
      - jq
    state: present

# - name: copy apache config into place
#   ansible.builtin.copy:
#     src: "{{ role_path }}/files/apache2.conf"
#     dest: /etc/apache2/

# - name: start apache
#   ansible.builtin.systemd:
#     enabled: true
#     state: started
#     name: apache

- name: create cronjob to write temperatur values to file
  ansible.builtin.cron:
    name: "15 minute cron to publish temperature readings as prometheus data"
    minute: "*/15"
    job: "temper.py --json | jq -r '.[0] | {\"external temperature\", \"internal temperature\"} | .[\"external\"] = .\"external temperature\" | .[\"internal\"] = .\"internal temperature\" | del(.\"internal temperature\" , .\"external temperature\") |keys_unsorted[] as $k |\"\\($k) \\(.[$k])\"' > /var/www/html/metrics"