---
# tasks file for sensor-setup

- name: update apt cache
  ansible.builtin.apt:
    update_cache: yes    

- name: install nginx
  ansible.builtin.apt:
    name: nginx
    state: present
  ignore_errors: true

- name: install jq
  ansible.builtin.apt:
    name: jq
    state: present

- name: install pip
  ansible.builtin.apt:
    name: python3-pip
    state: present

- name: install git
  ansible.builtin.apt:
    name: git
    state: present

- name: Remove EXTERNALLYMANAGED
  ansible.builtin.file:
    path: /usr/lib/python3.11/EXTERNALLY-MANAGED
    state: absent

- name: install bme688 software
  ansible.builtin.pip:
    name: bme680
  when:
    - sensor is defined
    - sensor == "bme688"

- name: create bme688 directory
  ansible.builtin.file:
    path: /opt/bme688/
    state: directory

- name: install bme688 examples
  ansible.builtin.git:
    repo: 'https://github.com/pimoroni/bme680-python'
    dest: /opt/bme688/
    bare: true
  when:
    - sensor is defined
    - sensor == "bme688"

- name: copy nginx config into place
  ansible.builtin.copy:
    src: "{{ role_path }}/files/nginx.conf"
    dest: /etc/nginx/nginx.conf

- name: copy metrics publishing script into place
  ansible.builtin.copy:
    src: "{{ role_path }}/files/publish-metrics.sh"
    dest: /usr/local/bin/publish-metrics.sh
    mode: 0755
  when:
    - sensor is defined
    - sensor == "temper"

- name: start nginx
  ansible.builtin.systemd:
    enabled: true
    state: restarted
    name: nginx

- name: sets PATH environment variable for crontab
  ansible.builtin.cron:
    name: PATH
    job: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    env: yes
    
- name: create cronjob to write temperatur values to file
  ansible.builtin.cron:
    name: "publish-promethus-data"
    minute: "*/15"
    job: "/usr/local/bin/publish-metrics.sh"
  when:
    - sensor is defined
    - sensor == "temper"