---
# tasks file for pihole-update

- name: update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: update managed system
  ansible.builtin.apt:
    name: "*"
    state: latest
  notify:
    - reboot managed system
  when:
    - controller is undefined

- name: update controller system
  ansible.builtin.apt:
    name: "*"
    state: latest
  notify:
    - reboot controller
  when:
    - controller is defined
    - controller | bool






