---
# tasks file for system-update

- name: install vim
  ansible.builtin.apt:
    name: vim
    state: latest

- name: update apt cache
  ansible.builtin.apt:
    update_cache: yes 

- name: update hosts file
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts   

- name: update managed system packages
  ansible.builtin.apt:
    name: "*"
    state: latest
  notify:
    - reboot managed system